---
apiVersion: v1
kind: Pod
metadata:
  name: webserver
  # namespace: twitter
  labels:
    app: nginx
    tier: front
    version: v1
    env: production
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80

